### ISSUE TITLE
pfe-cta reduce padding in narrow spaces

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#503] opened 2019-08-20 02:52 UTC
Perhaps by adding attribute `pfe-size="small"`
but even better would be to use element queries to detect container width.

**Comment by castastrophe** [comment] 2019-11-14 15:19
This feels like a dupe of https://github.com/patternfly/patternfly-elements/issues/437

**Closed by castastrophe** 2019-11-14 15:19 UTC
Labels: enhancement
