### ISSUE TITLE
Accordion header and panel max-width is less than 100%, causing an awkward misalignment

### ISSUE THREAD

**Issue by KrystalMoore16** [patternfly/patternfly-elements#1265] opened 2021-01-11 20:15 UTC
## Description of the issue

Accordion header and panel has a max-width of calc(100%-4px), causing both elements to appear 4px shy of the max width of the wrapper element. This causes visible misalignment. I can override the panel, but cannot override the header since the button is inside of the shadow root.

### Impacted component(s)

Accordion, but specifically the header and panel.

### Steps to reproduce

I don't have clear steps for you to reproduce as of yet since it became visible during preparation for an A/B test. See screenshot.

### Expected behavior

The element should fit the container it's in.

### Screenshots

![image](https://user-images.githubusercontent.com/14824271/104233045-35e74380-541f-11eb-8ae2-2bfc07e432e6.png)

Overriding the panel's max-width: 
![image](https://user-images.githubusercontent.com/14824271/104233088-47305000-541f-11eb-929b-29fa12968471.png)

**Comment by KrystalMoore16** [comment] 2021-01-11 20:20
@kylebuch8, my team is currently asking about switching this component out for the PF React version. I'm hoping this doesn't give them another reason for wanting to make that change :( TIA!

**Comment by castastrophe** [comment] 2021-01-23 14:01
The 4px adjusts for the 4px border that is present when the element is expanded so that is by design to prevent a flicker when the border is added or removed.

**Comment by kylebuch8** [comment] 2021-02-04 13:51
@KrystalMoore16 - I created a CodeSandbox that might help you.

https://codesandbox.io/s/brave-maxwell-vxkpg?file=/index.html

Here's what it looks like if you increase the width of `pfe-accordion` by 4px.

![image](https://user-images.githubusercontent.com/330256/106901616-fcc08d00-66c5-11eb-9139-3c49a95de597.png)

The CSS is fairly straight-forward.

```css
pfe-accordion: {
  width: calc(100% + 4px);
}
```

**Comment by KrystalMoore16** [comment] 2021-02-04 17:39
Hey @castastrophe, thanks for the clarification. Sorry, I missed your reply!

Thanks, @kylebuch8. That works. The alignment just feels a little wonky since it's the only element to exceed 100% width by 4px. Obviously this makes sense since we're telling it to do just that with your suggestion and it looks fine, but I was hoping for a solution that would let it naturally adapt to 100% width (matching its container) without needing any CSS on our end.

![image](https://user-images.githubusercontent.com/14824271/106929271-2daebb00-66e2-11eb-92b6-d39b81234ec3.png)

Not a big issue though. At the very least, this is a better approach than what we're currently doing. Much appreciated!

**Comment by castastrophe** [comment] 2021-02-04 18:09
When you get a chance @KrystalMoore16, can you message me a link to the dev environment?  I'd love to poke at it a bit and understand the context it is in better.

**Comment by KrystalMoore16** [comment] 2021-02-04 18:32
@castastrophe, can you access [this tool](https://access.qa.redhat.com/support/cases/#/troubleshoot/describe-issue?product=Red%20Hat%20Enterprise%20Linux&version=8.2&seSessionId=694052ec-0622-4c0e-b83f-ecdf62ecf2f1&tcSearch=true)? `tcSearch=true` in the URL brings up the use case that I reviewed. 

You'll just have to remove the margin-right that was applied to the toolbar above the accordion. It's not my favorite solution, but it worked with our deadline :)

**Comment by starryeyez024** [comment] 2021-03-30 17:56
@KrystalMoore16 I believe this has been resolved in 1.3.4.
Can you confirm? https://patternflyelements.com/elements/pfe-accordion/demo/

**Comment by starryeyez024** [comment] 2021-04-01 20:19
@KrystalMoore16  the accordions look good to me on that page and on the demo page. I'm going to close out this issue. :) 

![image](https://user-images.githubusercontent.com/456863/113349398-fa656280-9305-11eb-835b-e5593dea4eca.png)

**Closed by starryeyez024** 2021-04-01 20:19 UTC
Labels: bug, priority: high, size: sm, styles

**Comment by KrystalMoore16** [comment] 2021-04-05 15:16
Sorry for the delay; PTO last week.

@starryeyez024, it looks fine through the hack that @kylebuch8 provided. However, I don't feel like that adjustment should come from the teams implementing the component. It's not a _big_ deal, but it's also not _ideal_.

I can see this going the opposite way of course--like needing to reduce the width for some reason. I just can't wrap my head around having to force the accordion to expand to its parent's width. That's kind of an odd thing to override, no?

It may be fine on content pages, but being on an app dev team, we always need to consider space, flexibility, and ease-of-use for fast pace implementation at every corner. Our team had me to quickly patch this up before our release, but even I had to reach out first because I questioned why we were overriding something like this to begin with. Why not just eliminate that potential back-and-forth, hack, and confusion it causes altogether?

For example, the patch that my team came up with before I jumped in to add the solution above caused a misalignment for the other elements on the page. Teams will do anything to patch something in a hurry, even if it's not the right solution. Then, it'll just sit there until someone like me notices it visually or in the code :) Kyle's solution may seem like an easy fix for ya'll, but I guarantee that it'll cause more back-and-forth in the future between the PFE team and other app teams who are trying to fix it the "right" way like we did.

I hope that my feedback is seen in the most constructive way possible. Our issue is technically fixed with the patch above, so I could care less at this point other than for the desire to simplify code and to hopefully get ya'll to consider an app dev POV to make your lives easier as more teams consume PFE components.

Thanks again for your help and the consideration, team! Much appreciated.

**Comment by starryeyez024** [comment] 2021-04-05 15:29
Hey @KrystalMoore16, thanks for the feedback, and sorry I didn't realize that page had a hack. However we did recently fix the accordions themselves, so it's possible that the hack can be removed (and the version bumped to the latest) to remedy this problem. 

Can you check the demo page and see if this solves the issue "the right way" or if there is still a need here? Thx! https://patternflyelements.com/elements/pfe-accordion/demo/

**Comment by KrystalMoore16** [comment] 2021-04-05 16:42
No worries at all, @starryeyez024. Everything looks great after tinkering with it on the demo page!

We'll bump the version in our app soon to double check, but I think ya'll nailed it 👍 I'll only comment here again if bumping the version doesn't naturally fix it so that you're aware.

P.S. This demo page looks really nice :)

**Comment by starryeyez024** [comment] 2021-04-05 20:14
Awesome, thanks!
