### ISSUE TITLE
Bug: PFE-accordion on=dark not being set intermittently 

### ISSUE THREAD

**Issue by alazzara** [patternfly/patternfly-elements#1486] opened 2021-03-23 20:43 UTC
## Description of the issue
On this page in master `/elements/pfe-jump-links/demo/` the on dark section. The accordion styles will sometimes look as expected and other times it won't get the `on=dark` attribute. If you refresh a few times you will see it break and fix itself.

### Impacted component(s)

- PFE-accordion

### Steps to reproduce

1. Go to '/elements/pfe-jump-links/demo/'
2. Scroll to 'Accordion component on dark' or 'Accordion component on saturated' section
4. Click on 'accordion item'
5. Notice the accordion has a white background instead of gray.
6. If you inspect `<pfe-accordion>` you will notice it doesn't have `on="dark"` attribute.

### Expected behavior

You should see the accordion with a dark gray BG and when you inspect `<pfe-accordion>` you should see `on="dark"` attribute applied.

### Screenshots

Expected:
<img width="1171" alt="Screen Shot 2021-03-23 at 2 59 11 PM" src="https://user-images.githubusercontent.com/55710331/112215331-a61bfd80-8bf6-11eb-9cf9-10ecff372ac2.png">

Intermittent issue:
<img width="1215" alt="Screen Shot 2021-03-23 at 2 56 52 PM" src="https://user-images.githubusercontent.com/55710331/112215356-acaa7500-8bf6-11eb-9a06-e3f4974beaef.png">

## Related issues

- (#100) Description

**Comment by castastrophe** [comment] 2021-04-23 18:52
Just realized this #1438 was a dupe of this issue.  I'm going to close this one out since the other is already linked to the PR

**Closed by castastrophe** 2021-04-23 18:52 UTC
Labels: bug, priority: low, styles
