### ISSUE TITLE
[tools] Update rollup to include window.addEventListener wrapper

### ISSUE THREAD

**Issue by chrisdo1** [patternfly/patternfly-elements#324] opened 2019-02-13 19:45 UTC
```
window.addEventListener( "DOMContentLoaded", function( ){
});
```

**Comment by chrisdo1** [comment] 2019-02-13 19:46
```
window.addEventListener( "DOMContentLoaded", function( ){
});
```

**Comment by mwcz** [comment] 2019-02-14 15:15
I'll investigate rollup config to see if the global UMD case can be targeted without affecting CJS or AMD.

Brain dump for others or my future self:

### bug only affects the global case

UMD covers three ways of importing a file:

1. CommonJS
2. AMD (ex: RequireJS)
3. global ("plain script tags" is another way to think of this one)

This bug only affects global, and I don't want to adversely affect the performance of CJS and AMD by delaying their initialization when it isn't necessary.  I'm betting rollup offers a way to update the UMD template so we can wait for DOMContentLoaded only in the global case.

### global modules + DOMContentLoaded + dependencies

Another complexity to consider is that plain script tags are the only synchronous way to include elements.  When using plain script tags, dependency management is the developers' responsibility, meaning that script tags must be put in the right order.  It's tedious but it works because the scripts are synchronous: the dependency is guaranteed to be ready before the depender is run.  If we wait for DOMContentLoaded, the event loop ordering _should_ guarantee that everything is still run in the right order but I want to be sure.  That whole concern could be avoided by wrapping only the `PFElement.create(...)` call in DOMContentLoaded, but leaving the class outside, however that approach is harder to handle with rollup.  We'd need to do something more custom.

### But is it only global?

I'd like to do some tests to make sure it really does only affect the global case and that there isn't a race condition in the others.  Other module systems could be affected and we just aren't seeing it because the timing happens to line up well.  The test I'm imagining is to take the reproducer from yesterday and copy the offending element a bunch, like 10,000 times.  Then include the JS (without the fix) as ESM, AMD, and global and see where it breaks.  I have a small hunch that it will break everywhere.

**Comment by bennypowers** [comment] 2022-02-23 22:24
We dropped UMD and co in pfe-2.0 so i'm closing this

**Closed by bennypowers** 2022-02-23 22:24 UTC
Labels: tools, needs: prioritization, fix
