### ISSUE TITLE
[fix] pfe-jump-links | slot="pfe-jump-links-nav--heading" not working

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1734] opened 2021-07-30 00:06 UTC
## Description of the issue

I meant for both `slot="pfe-jump-links-nav--heading"` and `slot="heading"` to work on pfe-jump-links-nav but apparently only `slot="header"` is working at the moment.  On line 148, `this.getSlot(["heading", "pfe-jump-links-nav--heading"])[0];` should capture both.

### Impacted component(s)

- pfe-jump-links-nav

## Doesn't work
1. Create a `pfe-jump-links-nav`, add `<h3 slot="pfe-jump-links-nav--heading>Foo</h3>`.
2. Validate that it does not show up in the header, instead it will say "Jump to section".

## Does work
1. Create a `pfe-jump-links-nav`, add `<h3 slot="heading>Foo</h3>`.
2. Validate that "Foo" shows up in the header.

**Comment by heyMP** [comment] 2021-09-28 20:47
Update: Looks like this needs `Pfelement.getSlot()` to accept an array of slot names.  The old slot names are marked for deprecation in 2.0.  We've also migrated the slot names in our internal WebRH project.

**Comment by bennypowers** [comment] 2022-02-24 12:43
1. https://patternflyelements.org/components/jump-links/demo/
2. run this in console
```js
$('[slot="heading"]')
<h4 id="standard-section" slot="heading">

$('[slot="heading"]').parentElement
<pfe-jump-links-nav id="jumplinks1">

$('[slot="heading"]').slot = 'pfe-jump-links-nav--heading'
"pfe-jump-links-nav--heading"
```
I observed no change to the page layout - both 'heading' and (now deprecated pfe-jump-links-nav--heading' slots worked.

Closing as it appears fixed. If i'm mistaken about that please re-open with a reproduction for 2.0

**Closed by bennypowers** 2022-02-24 12:43 UTC
Labels: priority: low, priority: high, size: sm, needs: prioritization, fix
