### ISSUE TITLE
Pfe-Tooltip web component not displaying correctly

### ISSUE THREAD

**Issue by jaadbarg** [patternfly/patternfly-elements#2154] opened 2022-09-20 17:17 UTC
## Description of the issue

When the user hovers over the tooltip it displays a vague large black box without tooltip indication as to which element triggered it.  I noticed I was also unable to specify the positioning (left, right, top) of the tooltip as well.
### Impacted component(s)

- pfe-tooltip web component

### Steps to reproduce

1. Use code from example readme `https://github.com/patternfly/patternfly-elements/tree/main/elements/pfe-tooltip`
2. Hover over element/container which is supposed to trigger tooltip
3. See error where tooltip is large box without arrow.

### Expected behavior

When the user hovers over the intended trigger for the tooltip, it should render with an arrow pointing at what triggered it e.g. icon, button, etc.
### Screenshots

**Example 1: With Real Example**

![Recording 2022-09-20 at 12 24 54](https://user-images.githubusercontent.com/46633207/191312768-5257f65e-3299-4848-ad25-97426cbcdacc.gif)

----------------------------------------------------------------------------------------------------------------

**Example 2: With Readme Code**
![Recording 2022-09-20 at 12 28 27](https://user-images.githubusercontent.com/46633207/191313450-bb0e72dc-f1dc-4693-947c-83868d3ae547.gif)

**Comment by bennypowers** [comment] 2022-09-20 21:01
Thank you for moving this issue @jaadbarg.

Can you please open the browser console, refresh the page, and paste the output? I suspect the issue is that you need to add a script to the page somewhere before pfe-tooltip loads, with the following content:

```js
globalThis.process ??= { env: {} };
```

This is because pfe-tooltip currently uses a legacy 3rd party dependency. we're planning on removing it at some point, but the above snippet might be a helpful workaround in the mean time.

**Comment by jaadbarg** [comment] 2022-09-20 21:10
Ah that makes sense since this is the error I am seeing:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/46633207/191364484-2da1fb76-f398-4114-9f7c-97d8ec962d54.png">

I just added that in and everything is working as expected, thanks for the help!

**Comment by bennypowers** [comment] 2022-09-20 21:14
glad to help and sorry that our crufty 3rd party dependency assumes that "runs in the browser" _actually_ means "runs in node"

**Closed** 2022-09-21 01:16 UTC
Labels: priority: low, bug
