### ISSUE TITLE
cta demo file css issues

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#898] opened 2020-05-29 12:48 UTC
![image](https://user-images.githubusercontent.com/456863/83261209-fb2ee480-a188-11ea-8ec7-f7ec9918d769.png)

http://localhost:8000/elements/pfe-cta/demo/

**Comment by bennypowers** [comment] 2021-07-31 22:04
I couldn't reproduce this is it still relevant?
<img width="313" alt="Screen Shot 2021-08-01 at 1 04 03" src="https://user-images.githubusercontent.com/1466420/127753383-5c4ea237-8e61-4493-bb1a-9b0e35d834da.png">

**Comment by castastrophe** [comment] 2022-04-21 15:58
@bennypowers Likely not; I think you can close this one safely.

**Closed** 2022-04-24 07:20 UTC
Labels: good first issue, styles, priority: low, size: sm, needs: prioritization, fix
