### ISSUE TITLE
Styles not being created for components on a global npm run build

### ISSUE THREAD

**Issue by kylebuch8** [patternfly/patternfly-elements#1336] opened 2021-02-08 22:16 UTC
### Impacted component(s)
- A majority of the components

### Steps to reproduce

1. Run `npm run build` from the root of the project
2. Observe that the temp directory for the components don't all include a CSS file. I'm not sure why some do and some don't.

### Expected behavior
There should be CSS file in each of the temp directories.

### Screenshots
Demo pages
![image](https://user-images.githubusercontent.com/330256/107288148-f9643300-6a30-11eb-85d2-959483adc173.png)

This image shows pfe-band after the build command without a style tag in the HTML. You can also see that the _temp directory for pfe-avatar does not have a CSS file. 
![image](https://user-images.githubusercontent.com/330256/107288252-257fb400-6a31-11eb-85e5-5f85f336322c.png)

This issue is a release blocker for the next release.

**Comment by kylebuch8** [comment] 2021-02-08 22:17
This commit introduced the issue.
https://github.com/patternfly/patternfly-elements/commit/b16e425d87ac31b7bf7a1f245c48ff6defcb4bb0

Reverting line 6 fixes the issue.

**Comment by castastrophe** [comment] 2021-02-09 14:59
I think it's a little more complicated than just removing that line.  The issue is that pfe-sass is being rebuilt as a dependency of every component and that leads to a race condition that occasionally throws this error when a component tries to reference pfe-sass when another component is rebuilding it.  Specifically the globbing task.  I have some ideas for mitigating this and I'll chat with @mwcz a bit more today about lerna options.

**Comment by starryeyez024** [comment] 2021-02-09 16:40
@castastrophe  is it an option to revert `b16e425` as a quick path forward, and re-address the bigger picture issue after the release? How often were we seeing sass related build issues before the pfe-sass branch was merged?

**Comment by castastrophe** [comment] 2021-02-09 19:22
Like I said - it's not a fix because the build was still failing periodically before that.

**Comment by starryeyez024** [comment] 2021-02-09 19:49
Sure, but periodically or occasionally as noted in the [original PR](https://github.com/patternfly/patternfly-elements/pull/1322) is still an improvement over not at all.  In switching back to a commit before the sass updates, I can't reproduce any build errors when running `npm run build` so the release could be unblocked, and we can address the other issues later. Can you open a PR that rolls back those changes? Thanks!

**Comment by castastrophe** [comment] 2021-02-09 20:09
It wasn't just occasionally, the build was failing 4/10 times.  I'm mid-fix already for one that actually resolves the problem.

**Closed** 2021-02-09 23:22 UTC
Labels: bug, priority: high, tools
