### ISSUE TITLE
bug: pfe-accordion 2.0 doesn't work with normalize.css

### ISSUE THREAD

**Issue by heyMP** [patternfly/patternfly-elements#1914] opened 2022-03-08 20:15 UTC
## Description of the issue

Normalize.css contains some sane defaults that are interfering with how our elements that use [hidden].
 
### Impacted component(s)

- pfe-accordion (that we know of)

### Steps to reproduce

1. Go to https://codepen.io/heyMP/pen/LYOoMMP
2. Click on some of the headers.  You'll see that they expand only the first time.
3. Now inspect the panels to find this CSS declaration:

**Comment by bennypowers** [comment] 2022-03-09 02:42
if i understood this correctly, we're setting `hidden` on pfe-accordion header, but expecting it to still display?

**Comment by heyMP** [comment] 2022-03-09 12:37
I haven't looked into the code but I think it would work as expected if `[hidden]` is added to the panel prior to animating the open animation and after the close animation.

**Comment by bennypowers** [comment] 2022-03-09 16:26
Taking a look at this, I believe the root of the problem is that we rely on `transitionend` event. I suspect that normalize is setting some css that prevents that event from firing after the 1st cycle of opening/closing a panel.

I would like to try refactoring to use the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate), and see if that solves it

**Closed** 2022-03-15 20:04 UTC
Labels: priority: low
